[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 5, y = 5 }
dynamic_padding = false
decorations = "full"

[font]
normal = { family = "Hurmit Nerd Font Mono", style = "Regular" }
size = 11.0

[colors]
# Default colors
[colors.primary]
background = "0x1e1e1e" # Dark background color
foreground = "0xeeeeee" # Light foreground

# Normal colors
[colors.normal]
black = "0x1e1e1e" # Dark background
red = "0xd75f5f"   # Red
green = "0x5f875f" # Green
yellow = "0xd7afaf" # Yellow
blue = "0x5f87af"  # Blue
magenta = "0xaf5f87" # Magenta
cyan = "0x87afaf"  # Cyan
white = "0xe4e4e4" # White

# Bright colors
[colors.bright]
black = "0x4e4e4e" # Dark gray
red = "0xff6c6b"   # Bright red
green = "0x87af87" # Bright green
yellow = "0xffd75f" # Bright yellow
blue = "0x87afaf"  # Bright blue
magenta = "0xd7afaf" # Bright magenta
cyan = "0x87d7d7"  # Bright cyan
white = "0xffffff" # Bright white

# Cursor colors
[colors.cursor]
text = "0x1e1e1e" # Cursor text color
cursor = "0xeeeeee" # Cursor color

[bell]
animation = "EaseOutExpo"
duration = 0
color = "0xff0000" # Bell color (keeping it as is)

